spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: 
    name: microcloud-config-client1
eureka: 
  client:
    service-url:
      defaultZone: http://yangmi:ym@eureka-dev.com:7001/eureka
---
server:
  port: 8102
spring:
  profiles: beta
  application: 
    name: microcloud-config-client
eureka: 
  client:
    service-url:
      defaultZone: http://yangmi:ym@eureka-beta.com:7001/eureka